# Generated by Django 3.1.2 on 2020-10-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_turn', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('alive', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('attacking_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shot.attacking_team+', to='games.team')),
                ('defending_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shot.defending_team+', to='games.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('length', models.IntegerField()),
                ('direction', models.IntegerField(choices=[(0, 'North'), (1, 'South'), (2, 'East'), (3, 'West')])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='games.team')),
            ],
        ),
    ]
